# -*- coding: utf-8 -*-
"""advanced_recursion_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ymzfjQ--a2SGzQxWQCUKEBQ3Uii07tP4
"""

##Generate all subsequences using recursion (recusrsion tree and recursion flow are used):
nums = []
result = []
def func(index, subset):
  if index >= len(nums):
    result.append(subset.copy())
    return
  subset.append(nums[index])
  func(index + 1, subset)
  subset.pop()
  func(index + 1, subset)
##Example
nums = [5, 9, 7]
func(0, [])
print(result)             #T(c) is O(2**N),every elt has 2 operations pick/ not pick, total N, so 2**N, S(c) is O(N) as stack space cannot exceed N

##Generate subsequences using recursion where sum of subsequence is equal to target:
##Brute force solution
nums = []
result = []
def func(index, subset):
  if index >= len(nums):
    if sum(subset) == target:
      result.append(subset.copy())
    return
  subset.append(nums[index])
  func(index + 1, subset)
  subset.pop()
  func(index + 1, subset)
##Example
nums = [5, 9, 4]
target = 9
func(0, [])
print(result)     #T(c) & S(c) is same as above, O(2**N) and O(N) respectively

##Generate subsequences using recursion where sum of subsequence is equal to target:
##optimal solution
nums = []
result = []
def backtrack(index,total, subset):
  if total == k:
    result.append(subset.copy())
    return
  elif total > k:
    return
  if index >= len(nums):
    return
  subset.append(nums[index])
  sum = total + nums[index]
  backtrack(index + 1, sum, subset)
  e = subset.pop()
  sum = total - e
  backtrack(index + 1, sum, subset)

##Example
nums = [5, 9, 4]
target = 9
func(0, [])
print(result)         #T(c) = O(2**N) , S(c) = O(N)

##Check if there exist subsequences with sum k:return T/F and generate subsets
##Same logic as above only
nums = []
result = []
def backtrack(index,total, subset):
  if total == k:
    result.append(subset.copy())
    return True
  elif total > k:
    return False
  if index >= len(nums):
    return False
  subset.append(nums[index])
  sum = total + nums[index]
  pick = backtrack(index + 1, sum, subset)
  if pick == True:
    return True
  e = subset.pop()
  sum = total
  not_pick = backtrack(index + 1, sum, subset)
  return not_pick

##Example
nums = [5, 9, 4]
target = 9
func(0, [])
print(result)
print(backtrack(0, 0, []))

##Check if there exist subsequences with sum k:return T/F only, no need to generate subsets
##Same logic as above only
nums = []
def backtrack(index,total):
  if total == k:
    return True
  elif total > k:
    return False
  if index >= len(nums):
    return False
  sum = total + nums[index]
  pick = backtrack(index + 1, sum)
  if pick == True:
    return True
  sum = total
  not_pick = backtrack(index + 1, sum)
  return not_pick

##Example
nums = [5, 9, 4]
target = 9
print(backtrack(0, 0))      #T(c) = O(2**N) , S(c) = O(N)

##Count all subsequences where sum of subsequence is equal to target:
nums = []
def backtrack(index,total):
  if total == k:
    return 1
  elif total > k:
    return 0
  if index >= len(nums):
    return 0
  sum = total + nums[index]
  pick = backtrack(index + 1, sum)
  backtrack(index + 1, total)
  sum = total
  not_pick = backtrack(index + 1, sum)
  return pick + not_pick

##Example
nums = [5, 9, 4]
target = 9
print(backtrack(0, 0))        #T(c) = O(2**N) , S(c) = O(N)