# -*- coding: utf-8 -*-
"""GreedyAlgorithms_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8dmEYvD_9voOpvUudVXUkzqb2QEb1Kt
"""

##PROBLEM:assign max children with greed factors an array of cookies with value
##sort both arrays, assign cookies in (s[j] >= g[i]) way where 's' is cookies array & 'g' is greed array, stop when all children are satisfied / cookies are exhausted.
s = [2, 6, 8, 1, 4]
g = [4, 2, 7, 1, 2, 3]
n = len(g)
m = len(s)
g = sorted(g)
s = sorted(s)
count = 0
left, right = 0, 0
while left < n and right < m:
    if s[right] >= g[left]:
        count += 1
        left += 1
    right += 1
print(count)         #T(c) is O(nlogn + mlogm + m) ans S(c) is O(1)

"""Problem Statement

You are given:

A set of items, each with a value val[i] and a weight wt[i].

A knapsack with capacity W.

You can take fractions of items (not just whole items).

Goal: Maximize the total value in the knapsack.

Key Idea (Greedy Choice)

Compute value/weight ratio for each item.

Always pick the item with the highest ratio first.

If the entire item fits, take it fully.

Otherwise, take only the fraction that fits.
"""

##alternate solution:
class Solution:
  def __init__(self, val, wt):
    self.val = val
    self.wt = wt
    self.ratio = val/wt
  def fractional_knapsack(self, W, items):
    items.sort(key=lambda x: x.ratio, reverse=True)
    final_val = 0.0
    currW = 0.0
    for item in items:
      if currW + item.wt <= W:
        currW += item.wt
        final_val += item.val
      else:
        remain_wt = W - currW
        final_val += item.ratio * remain_wt
        break
    return final_val
#Example:
items = [Solution(60, 10), Solution(100, 20), Solution(100, 50), Solution(200, 50)]
W = 90
# Create a dummy Solution instance with valid values just to call the method
dummy_solution = Solution(1, 1)
print(f"Maximum value in Knapsack = {dummy_solution.fractional_knapsack(W, items)}")   #T(c) is O(nlogn) for sorting + O(n) for iteration, S(c) is O(1).

##PROBLEM: Greedy algorithm to find minimum number of coins:
M = 47 ##value to be using min no of coins
c = [1, 2, 5, 10, 20, 50, 100, 200, 500, 2000]   #pick min no of coins, and one coin can be picked many times
n = len(c)
result = []   #to store coins picked
for i in range(n-1, -1, -1):
  while M >= c[i]:
    M -= c[i]    #since coin is picked val subtracted from M
    result.append(c[i]) #append picked coin in result
print(result)      #T(c) is O(n) and S(c) is O(1)

##PROBLEM: Greedy algorithm to be used for change in return of lemonade at a stall for a no of customers:
def lemonadeChange(bills):
    five, ten = 0, 0
    for bill in bills:
        if bill == 5:
            five += 1
        elif bill == 10:
            if five >= 1:
                five -= 1
                ten += 1
            else:
                return False
        else:  # bill == 20
            if ten >= 1 and five >= 1:
                ten -= 1
                five -= 1
            elif five >= 3:
                five -= 3
            else:
                return False
    return True

# Example
print(lemonadeChange([5, 5, 5, 10, 20]))  #T(c) is O(N), S(c) is O(1).

"""Problem Statement

You are given n meetings with:

start[i] → start time of meeting i

end[i] → end time of meeting i

Only one meeting can happen in a room at a time.

A meeting can start exactly at the same time another ends.

Goal: Find the maximum number of meetings that can be scheduled in the room.

Greedy Strategy

Always pick the meeting that finishes earliest (smallest end time) → this leaves maximum space for later meetings.

Sort all meetings by their end times.

Iterate through them, and keep selecting meetings that start after (or at) the end of the last selected one.
"""

start = [1, 3, 0, 5, 8, 5]
end = [2, 4, 6, 7, 9, 9]

class Meeting:
  def __init__(self, start, end, position):
    self.start = start
    self.end = end
    self.position = position

n = len(start)
meet = [Meeting(start[i], end[i], i+1) for i in range(n)]   #to keep 0th position as 1 , we write i+1 at position
meet.sort(key=lambda x: (x.end, x.start))

result = []
count = 1    #we start count as 1 since first meet is already selected
result.append(meet[0].position)
last_time = meet[0].end

for i in range(1, n):
    if meet[i].start >= last_time:
        result.append(meet[i].position)
        count += 1
        last_time = meet[i].end

print("Maximum number of meetings:", count)
print("Scheduled meeting positions:", result)   #T(c) is O(N), also S(c) is O(N)

##altenate better code
def maxMeetings(start, end):
    n = len(start)
    meetings = sorted(zip(start, end), key=lambda x: x[1])  # sort by end time

    count = 0
    last_end = -1

    for s, e in meetings:
        if s > last_end:   # can attend this meeting
            count += 1
            last_end = e

    return count

# Example
start = [1, 3, 0, 5, 8, 5]
end   = [2, 4, 6, 7, 9, 9]
print(maxMeetings(start, end))

##PROBLEM: Greedy Algorithm Jump Game:
##You are given an array nums, where nums[i] represents the maximum jump length from index i.
def canJump(nums):
    farthest = 0
    for i in range(len(nums)):
        if i > farthest:  # can't reach this index
            return False
        farthest = max(farthest, i + nums[i])
    return True
nums = [3, 2, 1, 4, 0, 2, 1, 5]
print(canJump(nums))
nums = [3, 2, 1, 0, 0, 2, 1, 5]
print(canJump(nums))  #T(c) is O(N), S(c) is O(1)

##PROBLEM: Greedy Algorithm Jump Game 2:
##You are given an array nums, where nums[i] = maximum jump length from index i.
##Start at index 0.
##Goal: Find the minimum number of jumps required to reach the last index.
##(Assume it’s always possible to reach the end.)
def jump(nums):
    jumps = 0
    left, right = 0, 0

    while right < len(nums) - 1:
        farthest = 0     # farthest we can reach
        for i in range(left, right + 1):  #left to right pointer, right included
            farthest = max(farthest, i + nums[i])   #i + nums[i] e.g. index plus value at index
        left = right + 1
        right = farthest
        jumps += 1

    return jumps
nums = [2, 3, 1, 4, 1, 1, 1, 2]
print(jump(nums))   #T(c) is O(N),since entire lust is iterated only once, S(c) is O(1), no stack used

##alternate solution: ##using recursion:
def func(index,jump):
  if index >= last_index:
    return jump
  min_jump = float("inf")
  for i in range(index+1,last_index+1):
    if nums[index] >= i-index:
      min_jump = min(min_jump,func(i,jump+1))
  return min_jump
nums = [2, 3, 1, 4, 1, 1, 1, 2]
last_index = len(nums)-1
print(func(0,0))    #T(c) is O(N**N), since each index has N possibilities of jumps, S(c) is O(N) since we are using stack

"""Problem Statement

You are given two arrays:

arr[] → arrival times of trains

dep[] → departure times of trains

Each train needs a platform from its arrival to departure.
Goal: Find the minimum number of platforms required so that no train has to wait.

Greedy Approach

This is very similar to the interval scheduling overlap problem.

Steps:

Sort both arrays arr[] and dep[] separately.

Use two pointers:

i → for next arrival

j → for next departure

Keep a counter plat_needed:

If arr[i] <= dep[j] → a train arrives before the earliest departure → need one more platform → plat_needed += 1, i += 1

Else (arr[i] > dep[j]) → one train has departed → free one platform → plat_needed -= 1, j += 1

Track the maximum platforms needed at any time.
"""

def minPlatforms(arr, dep):
    n = len(arr)
    arr.sort()
    dep.sort()    ##both arrival and departure arrays are sorted

    plat_needed = 0
    result = 0
    i, j = 0, 0    #two pointer approach

    while i < n and j < n:
        if arr[i] <= dep[j]:      # arrival first (or tie)
            plat_needed += 1
            result = max(result, plat_needed)
            i += 1
        else:
            plat_needed -= 1      #departure first
            j += 1

    return result
arr = [900, 940, 950, 1100, 1500, 1800]
dep = [910,1200,1120,1130,1900,2000]

print(minPlatforms(arr, dep))  #T(c) O(nlogn + nlogn +n +n), since two sorts and two loops running, S(c) is O(1).

##alternate solution:
def parse_time(t):
    """Accepts 'HH:MM' strings or integers like 930, returns minutes since 00:00."""
    if isinstance(t, int):
        return (t // 100) * 60 + (t % 100)
    if isinstance(t, str):
        hh, mm = map(int, t.split(":"))
        return hh * 60 + mm
    raise ValueError("Unsupported time format")

def min_platforms(arrivals, departures):
    if len(arrivals) != len(departures):
        raise ValueError("arrivals and departures must be same length")

    A = sorted(parse_time(t) for t in arrivals)
    D = sorted(parse_time(t) for t in departures)

    i = j = 0
    platforms = max_platforms = 0
    n = len(A)

    while i < n and j < n:
        if A[i] <= D[j]:          # arrival first (or tie)
            platforms += 1
            max_platforms = max(max_platforms, platforms)
            i += 1
        else:                      # departure first
            platforms -= 1
            j += 1

    return max_platforms

# Example 1 (integer times)
arr = [900, 940, 950, 1100, 1500, 1800]
dep = [910, 1200, 1120, 1130, 1900, 2000]
print(min_platforms(arr, dep))  # 3

# Example 2 (HH:MM times + ties)
arr2 = ["09:00", "09:40", "09:50", "10:00"]
dep2 = ["09:00", "09:55", "10:10", "11:00"]
print(min_platforms(arr2, dep2))  # 3 (arrivals at 09:00 & 10:00 tie with departures)

