# -*- coding: utf-8 -*-
"""ML_Regressor_Pyspark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xc-HDRDHd8Z8GBjVZVdD8MbFmKUrhpJX
"""

!pip install pyspark
!pip install findspark

import findspark
findspark.init()

import pandas as pd
import matplotlib.pyplot as plt
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").appName("MyApp").getOrCreate()
print("SparkSession started successfully!")

import seaborn as sns
from seaborn import load_dataset

df1 = load_dataset('tips')
# Note: seaborn.load_dataset returns a pandas DataFrame, not a Spark DataFrame.
# To work with Spark, you would need to convert this pandas DataFrame to a Spark DataFrame.
df = spark.createDataFrame(df1)
df.show()

df.printSchema()

df.columns

# Handling Categorical Features
from pyspark.ml.feature import StringIndexer


indexer = StringIndexer(inputCol = "sex", outputCol = "sex_indexed")
df_r = indexer.fit(df).transform(df)
df_r.show()

indexer = StringIndexer(inputCols = ["smoker", "day", "time"], outputCols = ["smoker_indexed", "day_indexed", "time_indexed"])

df_r = indexer.fit(df_r).transform(df_r)

df_r.show(50)

df_r = df_r.drop("sex", "smoker", "day", "time")
df_r.show()

from pyspark.ml.feature import VectorAssembler

featureassembler = VectorAssembler(inputCols = ["total_bill", "size", "sex_indexed", "smoker_indexed", "day_indexed", "time_indexed"], outputCol = "Independent Features")
output = featureassembler.transform(df_r)
output.show()

output.select("Independent Features").show()

finalized_data = output.select("Independent Features", "total_bill")
finalized_data.show()

from pyspark.ml.regression import LinearRegression

train_data, test_data = finalized_data.randomSplit([0.75, 0.25])
regressor = LinearRegression(featuresCol = "Independent Features", labelCol = "total_bill")
regressor = regressor.fit(train_data)

regressor.coefficients

import numpy as np
np.shape(regressor.coefficients)

regressor.intercept

pred=regressor.evaluate(test_data)
pred.predictions.show()

print(pred.r2,pred.meanAbsoluteError,pred.meanSquaredError)

finalized_data.toPandas()

df2 = load_dataset('mpg')
# Note: seaborn.load_dataset returns a pandas DataFrame, not a Spark DataFrame.
# To work with Spark, you would need to convert this pandas DataFrame to a Spark DataFrame.
data = spark.createDataFrame(df2)
data.show()

data.printSchema()

data.columns

data.describe().toPandas().transpose()

from pyspark.sql.functions import when,lit,count,isnan,col
data.select([count(when(isnan(c)|col(c).isNull(),c)).alias(c) for c in data.columns]).show()

data.dtypes

data = data.drop('origin', 'model_year')
data.show()

# Check for NaN values in the relevant columns
from pyspark.sql.functions import isnan, col, count

# Columns used in VectorAssembler
feature_cols = ["cylinders", "displacement", "weight", "horsepower", "acceleration"]

# Select the count of NaN values for each feature column
nan_counts = data.select([count(when(isnan(col(c)), c)).alias(c) for c in feature_cols])

nan_counts.show()

# Now modify the VectorAssembler to handle invalid values
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression
from pyspark.ml.evaluation import RegressionEvaluator

# Set handleInvalid to 'skip' to drop rows with NaN values
featureassembler = VectorAssembler(inputCols = feature_cols, outputCol = "Independent Features", handleInvalid="skip")
output = featureassembler.transform(data)
output.show()

finalized_data = output.select("Independent Features", "mpg")
finalized_data.show()

from pyspark.ml.regression import LinearRegression

# Train test split
train_data, test_data = finalized_data.randomSplit([0.75, 0.25])
Regressor = LinearRegression(featuresCol='Independent Features' , labelCol="mpg")

Regressor = Regressor.fit(train_data)

# Use the Regressor trained on the MPG data to evaluate the test_data from the MPG data
pred = Regressor.evaluate(test_data) # Changed from regressor to Regressor
pred.predictions.show()

pred.r2, pred.meanAbsoluteError, pred.meanSquaredError

