# -*- coding: utf-8 -*-
"""pyspark_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FmS33kbWMBTJUijXZutw5n1u4vTmC_nQ
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Datacamp Pyspark Tutorial").config("spark.memory.offHeap.enabled","true").config("spark.memory.offHeap.size","10g").getOrCreate()

spark = SparkSession.builder.appName("Datacamp Pyspark Tutorial").config("spark.memory.offHeap.enabled","true").config("spark.memory.offHeap.size","10g").getOrCreate()

!gdown 1T6dZkJgu4QOBD0VOWJ_HNJE4SiI-3_zw
df = spark.read.csv('datalab_export_2025-05-16 12_58_19.csv',header=True,escape="\"")
df.head()

df.show(10,0)

"""##EDA

Let’s start by counting the number of rows in the DataFrame :
"""

df.count()   # we had downloaded only 100 rows of the data for free

"""How many unique customers are present in the DataFrame?"""

df.select('CustomerID').distinct().count()

"""What country do most purchases come from?

To find the country from which most purchases are made, we need to use the groupBy() clause in PySpark:
"""

from pyspark.sql.functions import *
from pyspark.sql.types import *

df.groupBy('Country').agg(countDistinct('CustomerID').alias('country_count')).orderBy(desc('country_count')).show()

"""When was the most recent purchase made by a customer on the e-commerce platform?

To find when the latest purchase was made on the platform, we need to convert the InvoiceDate column into a timestamp format and use the max() function in Pyspark:
"""

spark.sql("set spark.sql.legacy.timeParserPolicy=LEGACY")
df = df.withColumn('date',to_timestamp("InvoiceDate", 'yy/MM/dd HH:mm'))
df.select(max("date")).show()

"""When was the earliest purchase made by a customer on the e-commerce platform?

Similar to what we did above, the min() function can be used to find the earliest purchase date and time:
"""

df.select(min("date")).show()

"""Notice that the most recent and earliest purchases were made on the same day just a few hours apart. This means that the dataset we downloaded contains information of only purchases made on a single day.

##Data Processing

Now that we have analyzed the dataset and have a better understanding of each data point, we need to prepare the data to feed into the machine learning algorithm.

Let’s take a look at the head of the data frame once again to understand how the pre-processing will be done:
"""

df.show(5,0)

"""From the dataset above, we need to create multiple customer segments based on each user’s purchase behavior.

The variables in this dataset are in a format that cannot be easily ingested into the customer segmentation model. These features individually do not tell us much about customer purchase behavior.

Due to this, we will use the existing variables to derive three new informative features - recency, frequency, and monetary value (RFM).

RFM is commonly used in marketing to evaluate a client’s value based on their:

Recency: How recently has each customer made a purchase?
Frequency: How often have they bought something?
Monetary Value: How much money do they spend on average when making purchases?
We will now preprocess the data frame to create the above variables.

Recency
First, let’s calculate the value of recency - the latest date and time a purchase was made on the platform. This can be achieved in two steps:

i) Assign a recency score to each customer

We will subtract every date in the data frame from the earliest date. This will tell us how recently a customer was seen in the data frame. A value of 0 indicates the lowest recency, as it will be assigned to the person who was seen making a purchase on the earliest date.
"""

df = df.withColumn("from_date", lit("12/1/10 08:26"))
df = df.withColumn('from_date',to_timestamp("from_date", 'yy/MM/dd HH:mm'))

df2 = df.withColumn('from_date',to_timestamp(col('from_date'))).withColumn('recency',col("date").cast("long") - col('from_date').cast("long"))

"""ii) Select the most recent purchase

One customer can make multiple purchases at different times. We need to select only the last time they were seen buying a product, as this is indicative of when the most recent purchase was made:
"""

df2 = df2.join(df2.groupBy('CustomerID').agg(max('recency').alias('recency')),on='recency',how='leftsemi')

"""Let’s look at the head of the new data frame. It now has a variable called “recency” appended to it:"""

df2.show(5,0)

"""An easier way to view all the variables present in a PySpark DataFrame is to use its printSchema() function. This is the equivalent of the info() function in Pandas:"""

df2.printSchema()

"""Frequency

Let’s now calculate the value of frequency - how often a customer buys something on the platform. To do this, we just need to group by each CustomerID and count the number of items they purchased:
"""

df_freq = df2.groupBy('CustomerID').agg(count('InvoiceDate').alias('frequency'))

df_freq.show(5,0)

"""There is a frequency value appended to each customer in the DataFrame. This new DataFrame only has two columns, and we need to join it with the previous one:"""

df3 = df2.join(df_freq,on='CustomerID',how='inner')

df3.printSchema()

"""Monetary Value

Finally, let’s calculate monetary value - the total amount spent by each customer in the DataFrame. There are two steps to achieving this:

i) Find the total amount spent in each purchase:
Each CustomerID comes with variables called Quantity and UnitPrice for a single purchase:

To get the total amount spent by each customer in one purchase, we need to multiply Quantity with UnitPrice:
"""

m_val = df3.withColumn('TotalAmount',col("Quantity") * col("UnitPrice"))

"""ii) Find the total amount spent by each customer:

To find the total amount spent by each customer overall, we just need to group by the CustomerID column and sum the total amount spent:
"""

m_val = m_val.groupBy('CustomerID').agg(sum('TotalAmount').alias('monetary_value'))

"""Merge this DataFrame with the all the other variables:"""

finaldf = m_val.join(df3,on='CustomerID',how='inner')

finaldf.show(5,0)

"""Standardization:

Before building the customer segmentation model, let’s standardize the DataFrame to ensure that all the variables are around the same scale:
"""

from pyspark.ml.feature import VectorAssembler
from pyspark.ml.feature import StandardScaler

assemble=VectorAssembler(inputCols=[
    'recency','frequency','monetary_value'
], outputCol='features')

assembled_data=assemble.transform(finaldf)

scale=StandardScaler(inputCol='features',outputCol='standardized')
data_scale=scale.fit(assembled_data)
data_scale_output=data_scale.transform(assembled_data)

"""Run the following lines of code to see what the standardized feature vector looks like:"""

data_scale_output.select('standardized').show(2,truncate=False)

"""These are the scaled features that will be fed into the clustering algorithm.

##Step 5: Building the machine learning model:

Now that we have completed all the data analysis and preparation, let’s build the K-Means clustering model.

The algorithm will be created using PySpark’s machine learning API.

i) Finding the number of clusters to use
When building a K-Means clustering model, we first need to determine the number of clusters or groups we want the algorithm to return. If we decide on three clusters, for instance, then we will have three customer segments.

The most popular technique used to decide on how many clusters to use in K-Means is called the “elbow-method.”

This is done simply running the K-Means algorithm for a wide range of clusters and visualizing the model results for each cluster. The plot will have an inflection point that looks like an elbow, and we just pick the number of clusters at this point.

Let’s run the following lines of code to build a K-Means clustering algorithm from 2 to 10 clusters:
"""

from pyspark.ml.clustering import KMeans
from pyspark.ml.evaluation import ClusteringEvaluator
import numpy as np

cost = np.zeros(10)

evaluator = ClusteringEvaluator(predictionCol='prediction', featuresCol='standardized',metricName='silhouette', distanceMeasure='squaredEuclidean')

for i in range(2,10):
    KMeans_algo=KMeans(featuresCol='standardized', k=i)
    KMeans_fit=KMeans_algo.fit(data_scale_output)
    output=KMeans_fit.transform(data_scale_output)
    cost[i] = KMeans_fit.summary.trainingCost

"""With the codes above, we have successfully built and evaluated a K-Means clustering model with 2 to 10 clusters. The results have been placed in an array, and can now be visualized in a line chart:"""

import pandas as pd
import pylab as pl
df_cost = pd.DataFrame(cost[2:])
df_cost.columns = ["cost"]
new_col = range(2,10)
df_cost.insert(0, 'cluster', new_col)
pl.plot(df_cost.cluster, df_cost.cost)
pl.xlabel('Number of Clusters')
pl.ylabel('Score')
pl.title('Elbow Curve')
pl.show()

"""ii) Building the K-Means Clustering Model
From the plot above, we can see that there is an inflection point that looks like an elbow at three. Due to this, we will proceed to build the K-Means algorithm with four clusters:
"""

KMeans_algo=KMeans(featuresCol='standardized', k=3)
KMeans_fit=KMeans_algo.fit(data_scale_output)

"""3) Making Predictions:

Let’s use the model we created to assign clusters to each customer in the dataset:
"""

preds=KMeans_fit.transform(data_scale_output)
preds.show(5,0)

"""Notice that there is a “prediction” column in this DataFrame that tells us which cluster each CustomerID belongs to:

##Step 6: Cluster Analysis:

The final step in this entire tutorial is to analyze the customer segments we just built.

Run the following lines of code to visualize the recency, frequency, and monetary value of each CustomerID in theDataFrame:
"""

import matplotlib.pyplot as plt
import seaborn as sns

df_viz = preds.select('recency','frequency','monetary_value','prediction')
df_viz = df_viz.toPandas()
avg_df = df_viz.groupby(['prediction'], as_index=False).mean()

list1 = ['recency','frequency','monetary_value']

for i in list1:
    sns.barplot(x='prediction',y=str(i),data=avg_df)
    plt.show()

"""Here is an overview of characteristics displayed by customers in each cluster:

Cluster 0: Customers in this segment display high recency, medium frequency, and low monetary value; so the e-commerce company should try to upsell products to this cluster.

Cluster 1: Users in this cluster display low recency, high frequency and high monetary value; so they can be given offers like loyalty programs for better recency.

Cluster 2: Customers in this segment display medium recency, low frequency and low monetary value; the company an consider not to target this cluster of customers.

Code for Binary Classification
"""

from pyspark.sql import SparkSession
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import BinaryClassificationEvaluator

# Start Spark session
spark = SparkSession.builder.appName("LogisticRegressionExample").getOrCreate()

# Load and preprocess data
data = spark.read.csv("data.csv", header=True, inferSchema=True)
assembler = VectorAssembler(inputCols=[col for col in data.columns if col != "label"], outputCol="features")
data = assembler.transform(data).select("features", "label")

# Split the data
train_data, test_data = data.randomSplit([0.7, 0.3], seed=42)

# Train the model
lr = LogisticRegression(featuresCol="features", labelCol="label")
lr_model = lr.fit(train_data)

# Make predictions
predictions = lr_model.transform(test_data)
predictions.select("features", "label", "prediction", "probability").show(5)

# Evaluate the model
evaluator = BinaryClassificationEvaluator(rawPredictionCol="rawPrediction", labelCol="label", metricName="areaUnderROC")
auc = evaluator.evaluate(predictions)
print(f"Area Under ROC: {auc}")