# -*- coding: utf-8 -*-
"""SlidingWindows_TwoPointers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihGBQ7ONEdO1H-1KYAukt5XKfEjM5h0D
"""

##Problem - Find Longest Substring Without Repeating Characters:
##Brute force solution:
##In order to avoid duplicacy we use a Set
s = ['C', 'A', 'D', 'B', 'Z', 'A', 'B', 'C', 'D']
n = len(s)
maxi = 0
for i in range(0,n):
  my_set = []
  for j in range(i,n):
    if s[j] in my_set:
      break
    else:
      my_set.append(s[j])
  maxi = max(maxi, j-i+1) ##where len(my_set) is j-i+1
print(maxi)               ##T(c) is O((N*(N+1))//2) ~ O(N**2) and S(c) is O(N)

##optimal Solution:
s = ['C', 'A', 'D', 'B', 'Z', 'A', 'B', 'C', 'D']
n = len(s)
maxi = 0
left = 0
right = 0
my_dict = {}
while right < n:
    if s[right] not in my_dict:
        maxi = max(maxi, right-left+1)
        my_dict[s[right]] = right ##value updaed with s[right] and key updated with index of right in a line
        right += 1
    elif s[right] in my_dict:
        left = max(left, my_dict[s[right]] + 1)
        maxi = max(maxi, right-left+1)
        my_dict[s[right]] = right
        right += 1
print(maxi)   #T(c) = S(c) = O(N)

##PROBLEM: Max Consecutive One's:
##Brute force solution:
nums = [1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0]
n = len(nums)
maxi = 0
k = 2
for i in range(0,n):
  zeros = 0
  for j in range(i,n):
    if nums[j] == 0:
      zeros += 1
    if zeros > k:
      break
    maxi = max(maxi, j-i+1)
print(maxi)      #T(c) is approx O(N**2) as there are two loops 'i' & 'j', S(c) is O(1)

##better solution: using sliding windows:
nums = [1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0]
n = len(nums)
maxi = 0
k = 2
zeros = 0
left = 0

for right in range(0,n):     #first iteration loop
    if nums[right] == 0:
        zeros += 1
    # shrink window if more than k zeros, second iteration loop
    while zeros > k:
        if nums[left] == 0:
            zeros -= 1
        left += 1
    # update answer
    maxi = max(maxi, right - left + 1)

print(maxi)  ##T(c) is O(2N) as we might need to iterate twice, S(c) is O(1)

##optimal solution: using sliding windows:
nums = [1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0]
n = len(nums)
maxi = 0
k = 2
zeros = 0
left = 0

for right in range(0,n):
    if nums[right] == 0:
        zeros += 1

    # this time we are moving windows left and right forward and not shrinking, while loop replaced by if condition
    if zeros > k:
        if nums[left] == 0:
            zeros -= 1
        left += 1
    if zeros <= k:
      maxi = max(maxi, right - left + 1)

print(maxi)   ##T(c) is O(N) since now no while loop so not running twice

##PROBLEM: Fruits in Basket:
##One can add max two types of fruits in basket, we need to find max_length of such a sub-array of two types of elements in a given array
nums = [3, 3, 3, 1, 2, 1, 1, 2, 3, 3, 4]
n = len(nums)
max_length = 0
for i in range(0,n):
  my_set = set()
  for j in range(i,n):
    my_set.add(nums[j])
    if len(my_set) > 2:  #max two types of fruits
      break
    max_length = max(max_length, j-i+1)
print(max_length)    #two loops running, so T(c) ~ O(N**2), S(c) is O(3), as it is a set, so const space

##better solution:
nums = [3, 3, 3, 1, 2, 1, 1, 2, 3, 3, 4]
n = len(nums)
max_length = 0
my_dict = {}
left = 0
right = 0
while right < n:
  my_dict[nums[right]] = my_dict.get(nums[right], 0) + 1
  while len(my_dict) > 2:   #two while loops running, also we take max two types fruits in basket, k =2
    my_dict[nums[left]] -= 1
    if my_dict[nums[left]] == 0:
      del my_dict[nums[left]]
    left += 1
  max_length = max(max_length, right - left + 1)
  right += 1
print(max_length)  #two loops running, so T(c) ~ O(2N), S(c) is O(2), as it is a dict with max two values

##optimal solution:
nums = [3, 3, 3, 1, 2, 1, 1, 2, 3, 3, 4]
n = len(nums)
max_length = 0
my_dict = {}
left = 0
right = 0
while right < n:
  my_dict[nums[right]] = my_dict.get(nums[right], 0) + 1
  if len(my_dict) > 2:         #max two types fruits in basket, k =2
    my_dict[nums[left]] -= 1
    if my_dict[nums[left]] == 0:
      del my_dict[nums[left]]
    left += 1
  if len(my_dict) <= 2:
     max_length = max(max_length, right - left + 1)
  right += 1
print(max_length)  #two loops running, so T(c) is O(N),while loop runs only once S(c) is O(2), as it is a dict with max two values

##PROBLEM: Maximum Points You Can Obtain from Cards
##You can pick any 3 cards at a time
nums = [1, 2, 3, 4, 5, 6, 1]
n = len(nums)
k = 3          #max 3 cards at a time, their sum
left_sum, right_sum = 0, 0
if n == k:
   print(sum(nums))
for i in range(0,k):
  left_sum += nums[i]
maxi = left_sum
right_index = n-1
for i in range(k-1, -1, -1):
  left_sum -= nums[i]
  right_sum += nums[right_index]
  maxi = max(maxi, left_sum + right_sum)
  right_index -= 1
print(maxi)        ##T(c) is O(2N), S(c) is O(1)

##alternative code:
nums = [1, 2, 3, 4, 5, 6, 1]
n = len(nums)
k = 3

left_sum = sum(nums[:k])   # take all k from left initially
maxi = left_sum

right_sum = 0
for i in range(1, k+1):   # take i cards from right
    right_sum += nums[-i]     # add one more from right
    left_sum -= nums[k-i]     # remove one from left
    maxi = max(maxi, left_sum + right_sum)

print(maxi)

